# Generated by Django 2.2.2 on 2019-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190624_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
