# Generated by Django 2.2.2 on 2019-07-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
