# Generated by Django 2.2.2 on 2019-08-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='polaratiy',
        ),
    ]
