# Generated by Django 2.2.2 on 2019-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190801_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='polaratiy',
        ),
        migrations.AddField(
            model_name='comment',
            name='polaraity',
            field=models.IntegerField(default=0),
        ),
    ]
