# Generated by Django 2.2.2 on 2019-08-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190801_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='polaraity',
            new_name='polarity',
        ),
    ]
