# Generated by Django 2.2.2 on 2019-08-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190801_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
