# Generated by Django 2.2.2 on 2019-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
    ]
