# Generated by Django 2.2.2 on 2019-07-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProflie',
        ),
    ]
